module.exports = {
    wrong_refercode : "کد معرفی اشتباه است",
    fill_fields : "لطفا فیلدها را پر کنید",
    refercode_oblige : "در اولین ورود کد معرفی الزامی است",
    code_sent : "کد تایید پیامک شد",
    mobile_count : "شماره موبایل ۱۱ عدد می‌باشد",
    mobile_09 : "شماره موبایل با ۰۹ آغاز می‌شود",
    user_exists : "کد تایید پیامک شد",
    supplier_exists: "کد تایید پیامک شد",
    user_registered : "ثبت نام با موفقیت انجام شد",
    supplier_registered:"ویزیتور با موفقیت انجام شد",
    item_registered:"محصول ثبت شد",
    item_updated:"محصول تغییر کرد",
    internal_server : "خطای سرور رخ داده است",
    user_not_found : "کاربر پیدا نشد",
    supplier_added : "ویزیتور اضافه شد",
    wrong_refer_code : "کد معرفی اشتباه است",
    item_added : "سفارش ثبت شد",
    order_removed : "سفارش حذف شد",
    wrong_confirmcode : "کد تایید اشتباه است",
    item_has_order : "سفارشی برای این محصول وجود دارد ابتدا آن را پاک کنید",
    user_has_order : "شما چند سفارش باز از این ویزیتور دارید. ابتدا آن ها راحذف کنید",
    supplier_removed : "ویزیتور حذف شد",
    item_removed : "محصول پاک شد",
    no_result_found : "نتیجه ای پیدا نشد",
    done: "ثبت شد",
    repeated_code:"کد تکراری است"

};