module.exports = {
    wrong_refercode : "کد معرفی اشتباه است",
    fill_fields : "لطفا فیلدها را پر کنید",
    code_sent : "کد تایید پیامک شد",
    mobile_count : "شماره موبایل ۱۱ عدد می‌باشد",
    mobile_09 : "شماره موبایل با ۰۹ آغاز می‌شود",
    user_exists : "کاربر قبلا ثبت شده است",
    user_registered : "ثبت نام با موفقیت انجام شد",
    supplier_registered:"ثبت تامین کننده با موفقیت انجام شد",
    item_registered:"کالا ثبت شد",
    internal_server : "خطای سرور رخ داده است",
    user_not_found : "کاربر پیدا نشد",
    supplier_added : "تامین کننده اضافه شد",
    item_added : "سفارش ثبت شد",
    order_removed : "سفارش حذف شد",
    wrong_confirmcode : "کد تایید اشتباه است",
};